# Generated by Django 4.2.1 on 2023-05-11 21:56

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.course_avatars_path),
        ),
    ]
