# Generated by Django 4.2.1 on 2023-07-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_courses_options_alter_courseteacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category'),
        ),
    ]
