# Generated by Django 3.2.20 on 2023-09-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_courseteacher_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='cost',
            new_name='price',
        ),
    ]
